name: C++ CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build project
        run: |
          g++ -o app progin/progin.cpp

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: compiled-app
          path: app